<a href="https://colab.research.google.com/github/Komal-99/Reinforcement-Learning/blob/main/Q_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
#R matrix
R=np.matrix([[-1,-1,-1,-1,0,-1],
              [-1,-1,-1,0,-1,100],
              [-1,0,0,-1,0,-1],
              [-1,0,0,-1,0,-1],
              [-1,0,0,-1,-1,100],
              [-1,0,-1,-1,0,100]])

In [2]:
R

matrix([[ -1,  -1,  -1,  -1,   0,  -1],
        [ -1,  -1,  -1,   0,  -1, 100],
        [ -1,   0,   0,  -1,   0,  -1],
        [ -1,   0,   0,  -1,   0,  -1],
        [ -1,   0,   0,  -1,  -1, 100],
        [ -1,   0,  -1,  -1,   0, 100]])

In [3]:
R.shape

(6, 6)

In [4]:
Q=np.matrix(np.zeros([6,6]))

In [5]:
Q


matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [6]:
gamma =0.8
initial_state=1

In [7]:
#this function returns all availaible actions in the statte given as argument
def available_actions(state):
  current_state_row=R[state,]
  av_act=np.where(current_state_row>=0)[1]
  return av_act

In [8]:
#get available actions in the cuurent state
available_act=available_actions(initial_state)

In [9]:
available_act

array([3, 5])

In [10]:
#checkimg on all state values
for i in range (len(R)):
  available_act1=available_actions(i)
  print("State",i,"--",available_act1)

State 0 -- [4]
State 1 -- [3 5]
State 2 -- [1 2 4]
State 3 -- [1 2 4]
State 4 -- [1 2 5]
State 5 -- [1 4 5]


In [11]:
#this function chooses at random which action to be performed with
def sample_next_action(available_actions_range):
  next_action=int(np.random.choice(available_act,1))
  return next_action

In [12]:
#sample next action to be performed
action=sample_next_action(available_act)

In [13]:
action

5

In [17]:
#this function updates the q matrix according to the path selected
def update(current_state,action,gamma):
  max_index=np.where(Q[action,]==np.max(Q[action,]))[1]
  if max_index.shappe[0]>1:
    max_index=int(np.random.choice(max_index,size=1))
  else:
    max_index=int(max_index)
    max_value=Q[action,max_index]
    # Q learning formula
    Q[current_state,action]=R[current_state,action]+gamma*max_value
#update Q value matrix
update(initial_state,action,gamma)

AttributeError: ignored

In [18]:
Q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [16]:
# Training
# train over 10,000 iterations
for i in range(10000):
  current_state=np.random.randint(0,int(Q.shape[0]))
  available_act=available_actions(current_state)
  action=sample_next_action(available_act)
  update(current_state,action,gamma)

AttributeError: ignored

In [ ]:
Q
