<a href="https://colab.research.google.com/github/Komal-99/Reinforcement-Learning/blob/main/Q_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
#R matrix
R=np.matrix([[-1,-1,-1,-1,0,-1],
              [-1,-1,-1,0,-1,100],
              [-1,0,0,-1,0,-1],
              [-1,0,0,-1,0,-1],
              [-1,0,0,-1,-1,100],
              [-1,0,-1,-1,0,100]])

In [20]:
R

matrix([[ -1,  -1,  -1,  -1,   0,  -1],
        [ -1,  -1,  -1,   0,  -1, 100],
        [ -1,   0,   0,  -1,   0,  -1],
        [ -1,   0,   0,  -1,   0,  -1],
        [ -1,   0,   0,  -1,  -1, 100],
        [ -1,   0,  -1,  -1,   0, 100]])

In [21]:
R.shape

(6, 6)

In [22]:
Q=np.matrix(np.zeros([6,6]))

In [23]:
Q


matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [24]:
gamma =0.8
initial_state=1

In [25]:
#this function returns all availaible actions in the statte given as argument
def available_actions(state):
  current_state_row=R[state,]
  av_act=np.where(current_state_row>=0)[1]
  return av_act

In [26]:
#get available actions in the cuurent state
available_act=available_actions(initial_state)

In [27]:
available_act

array([3, 5])

In [28]:
#checkimg on all state values
for i in range (len(R)):
  available_act1=available_actions(i)
  print("State",i,"--",available_act1)

State 0 -- [4]
State 1 -- [3 5]
State 2 -- [1 2 4]
State 3 -- [1 2 4]
State 4 -- [1 2 5]
State 5 -- [1 4 5]


In [29]:
#this function chooses at random which action to be performed with
def sample_next_action(available_actions_range):
  next_action=int(np.random.choice(available_act,1))
  return next_action

In [30]:
#sample next action to be performed
action=sample_next_action(available_act)

In [31]:
action

5

In [40]:
#this function updates the q matrix according to the path selected
def update(current_state,action,gamma):
  max_index=np.where(Q[action,]==np.max(Q[action,]))[1]
  if max_index.shape[0]>1:
    max_index=int(np.random.choice(max_index,size=1))
  else:
    max_index=int(max_index)
  max_value=Q[action,max_index]
    # Q learning formula
  Q[current_state,action]=R[current_state,action] + gamma*max_value
#update Q value matrix
update(initial_state,action,gamma)

In [41]:
Q

matrix([[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0., -1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [42]:
# Training
# train over 10,000 iterations
for i in range(10000):
  current_state=np.random.randint(0,int(Q.shape[0]))
  available_act=available_actions(current_state)
  action=sample_next_action(available_act)
  update(current_state,action,gamma)

In [43]:
Q


matrix([[  0.,   0.,   0.,   0., 400.,   0.],
        [  0.,  -1.,   0., 320.,   0., 500.],
        [  0., 400., 320.,   0., 400.,   0.],
        [  0., 400., 320.,   0., 400.,   0.],
        [  0., 400., 320.,   0.,   0., 500.],
        [  0., 400.,   0.,   0., 400., 500.]])

In [37]:
print("Trained Q matrix")


Trained Q matrix


In [44]:
#testing 
#goal state=5
current_state=1
steps=[current_state]
while current_state !=5:
  next_step_index=np.where(Q[current_state,]==np.max(Q[current_state,]))[1]
  if next_step_index.shape[0]>1:
    next_step_index=int(np.random.choice(next_step_index,size=1))
  else:
    next_step_index=int(next_step_index)
  steps.append(next_step_index)
  current_state=next_step_index

In [45]:
steps

[1, 5]